### 상품 등록
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "sellerId": 1,
  "name" : "name",
  "price" : 1000
}

### 완료된 주문 buyerId로 조회하기
GET http://localhost:8080/api/v1/products/purchase
Content-Type: application/json

{
  "buyerId": 16
}